version: '3'
services:
  nginx:
    build: docker/nginx
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/logs/:/var/log/nginx
      - .:/var/www/jobs
  php:
    build: docker/php
    restart: always
    volumes:
      - .:/var/www/jobs
  db:
    image: mysql:8.0.12
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: jobs
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
  composer:
    image: composer:1.7.2
    volumes:
      - ".:/app"
    command: install